spring:
  application:
    name: JDBL 86

  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true

  redis:
    host: localhost
    port: 6379
#    password:

aspect:
  logging: true